FROM httpd:latest
COPY ./httpd-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf
COPY ./index1.html /usr/local/apache2/docs/site1/index.html
COPY ./index2.html /usr/local/apache2/docs/site2/index.html